.PHONY: makeobj
makeobj: $(OBJDIR) $(OBJS)

INC_PARAMS:=$(INCLUDES:%=-I%)

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp
	$(CC) $(CFLAGS) $(CXXFLAGS) $(LIBDIRS) $(INC_PARAMS) -c $< -o $@ $(LDFLAGS)

$(OBJDIR):
	mkdir -p $(OBJDIR)

.PHONY: clean
clean:
	rm -rf $(OBJDIR)/*.o $(OBJDIR)/*.a $(OBJDIR)/*.exe
