PACKAGE_NAME:=sudokutest

INCLUDES:= \
	../include \
	include \
	googletest/include

LIBDIRS:=\
	../lib/obj

LDFLAGS:=\
	-lsudoku

SRC:=\
	main.cpp \
	SudokuUtilCheckerTest.cpp
	#SudokuPuzzleTest.cpp

UNITTEST:=true

include ../MakeHelper/Makefile.extra
include ../MakeHelper/Makefile.submake