INCLUDES:= \
	./../include \
	googletest/include \
	googletest/include/gtest \
	googletest/include/gtest/internal \
	googletest/include/gtest/internal/custom \

UTLIBDIRS:=\
	./../lib/obj

UTLDFLAGS:=\
	-lsudoku

SRC:=\
	SudokuUtilCheckerTest.cpp

UNITTEST:=true

include ../MakeHelper/Makefile.extra
include ../MakeHelper/Makefile.submake